// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoGSkp4bhT9hoHEICjRu39-wsx_7yxks',
    appId: '1:219757299500:web:8e8f0645422ada30628e89',
    messagingSenderId: '219757299500',
    projectId: 'mobile-d2b66',
    authDomain: 'mobile-d2b66.firebaseapp.com',
    databaseURL: 'https://mobile-d2b66-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-d2b66.firebasestorage.app',
    measurementId: 'G-X2Z9CWFYMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDxPhpFBhtmQlHIE8A1XGbCoB5F0GkaA',
    appId: '1:589262777369:android:ca48a799060469df330e88',
    messagingSenderId: '589262777369',
    projectId: 'ecolife-1c2ea',
    storageBucket: 'ecolife-1c2ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWY3K64uXtphW4TNoXp57p50Gv6T9qltA',
    appId: '1:219757299500:ios:ef1b36dd3e1925e1628e89',
    messagingSenderId: '219757299500',
    projectId: 'mobile-d2b66',
    databaseURL: 'https://mobile-d2b66-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-d2b66.firebasestorage.app',
    iosBundleId: 'com.example.assignmentTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWY3K64uXtphW4TNoXp57p50Gv6T9qltA',
    appId: '1:219757299500:ios:ef1b36dd3e1925e1628e89',
    messagingSenderId: '219757299500',
    projectId: 'mobile-d2b66',
    databaseURL: 'https://mobile-d2b66-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-d2b66.firebasestorage.app',
    iosBundleId: 'com.example.assignmentTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKoGSkp4bhT9hoHEICjRu39-wsx_7yxks',
    appId: '1:219757299500:web:019a6eef0c9455d0628e89',
    messagingSenderId: '219757299500',
    projectId: 'mobile-d2b66',
    authDomain: 'mobile-d2b66.firebaseapp.com',
    databaseURL: 'https://mobile-d2b66-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-d2b66.firebasestorage.app',
    measurementId: 'G-02E6TC484M',
  );
}